addr: :8765
minio:
  endpoint: minio.onlyquant.top
  accessKeyID: 2EugvoLWSgyJDZ
  bucket: journal
  secure: true
  expiry: 120h
route:
  back:
    base: "/api"
  front:
    dir: "dist"
    index: "dist/index.html"
db:
  name: journal_test
  host: postgres
  port: 5432
  username: onlyquant
